name: Feature Request
description: Request a new feature
labels: ["enhancement", "awaiting triage"]
assignees:
  - krlmrr
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What would you like us to add?
      description: What problem will this solve?
      placeholder: What do you expect to see?
    validations:
      required: true